# Generated by Django 3.1.6 on 2021-11-07 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='timeout',
        ),
        migrations.AddField(
            model_name='service',
            name='d_timeout',
            field=models.IntegerField(default=30, help_text='В минутах', verbose_name='Частота обновления'),
        ),
        migrations.AddField(
            model_name='service',
            name='w_timeout',
            field=models.IntegerField(default=10080, help_text='В минутах', verbose_name='Частота обновления'),
        ),
    ]
