# Generated by Django 3.1.6 on 2021-11-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20211109_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='b_timeout',
            field=models.IntegerField(default=10080, help_text='В минутах', verbose_name='Частота обновления (больше)'),
        ),
        migrations.AddField(
            model_name='service',
            name='rsi_b',
            field=models.CharField(default='25', max_length=130, verbose_name='RSI больше'),
        ),
        migrations.AlterField(
            model_name='service',
            name='d_timeout',
            field=models.IntegerField(default=30, help_text='В минутах', verbose_name='Частота обновления (дневной)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='w_timeout',
            field=models.IntegerField(default=10080, help_text='В минутах', verbose_name='Частота обновления (недельный)'),
        ),
    ]
