# Generated by Django 3.1.6 on 2021-11-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20211115_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='bd_timeout',
            field=models.IntegerField(default=10080, help_text='В минутах', verbose_name='Частота обновления дневной (больше)'),
        ),
        migrations.AddField(
            model_name='service',
            name='rsi_bd',
            field=models.CharField(default='25', max_length=130, verbose_name='RSI дневной (больше)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='b_timeout',
            field=models.IntegerField(default=10080, help_text='В минутах', verbose_name='Частота обновления недельный(больше)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='rsi_b',
            field=models.CharField(default='25', max_length=130, verbose_name='RSI недельный (больше)'),
        ),
    ]
