# Generated by Django 3.1.6 on 2021-04-21 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130, verbose_name='Наименование кнопки')),
                ('text', models.TextField(blank=True, help_text='Текст , который увидит пользователь , после нажатия кнопки', verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Кнопку',
                'verbose_name_plural': 'Кнопки',
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('key', models.CharField(help_text='Служебное поле', max_length=130, verbose_name='Ключ')),
                ('value', models.CharField(max_length=130, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Настройку',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.CreateModel(
            name='ButtonMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image', verbose_name='Изображение')),
                ('button', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='config.button', verbose_name='Кнопка')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.CreateModel(
            name='ButtonFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='file/', verbose_name='Файл')),
                ('button', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='config.button', verbose_name='Кнопка')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
    ]
