# Generated by Django 3.1.6 on 2021-04-22 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_auto_20210422_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buttonfile',
            old_name='image',
            new_name='file',
        ),
    ]
