# Generated by Django 3.1.7 on 2021-05-14 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_auto_20210422_1820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='button',
            options={'ordering': ['sort'], 'verbose_name': 'Кнопку', 'verbose_name_plural': 'Кнопки'},
        ),
        migrations.AddField(
            model_name='button',
            name='sort',
            field=models.IntegerField(default=0, help_text='Чем меньше число, тем выше кнопка', verbose_name='Сортировка'),
        ),
        migrations.CreateModel(
            name='InlineButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130, verbose_name='Назавние кнопки')),
                ('text', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(blank=True, upload_to='inline/', verbose_name='Изображение')),
                ('sort', models.IntegerField(default=0, help_text='Чем меньше число, тем выше кнопка', verbose_name='Сортировка')),
                ('button', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inlines', to='config.button')),
            ],
            options={
                'verbose_name': 'Инлайн кнопка',
                'verbose_name_plural': 'Инлайн кнопки',
                'ordering': ['sort'],
            },
        ),
    ]
