# Generated by Django 3.1.7 on 2021-05-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_auto_20210515_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='value',
            field=models.TextField(help_text='Максимум 400 символов.', max_length=400, verbose_name='Значение'),
        ),
    ]
