# Generated by Django 3.1.6 on 2021-09-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('address', models.CharField(max_length=130, verbose_name='Адрес')),
                ('work', models.CharField(max_length=130, verbose_name='Время работы')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('long', models.FloatField(verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.RemoveField(
            model_name='buttonfile',
            name='button',
        ),
        migrations.RemoveField(
            model_name='buttonmedia',
            name='button',
        ),
        migrations.DeleteModel(
            name='Division',
        ),
        migrations.RemoveField(
            model_name='inlinebutton',
            name='button',
        ),
        migrations.DeleteModel(
            name='Button',
        ),
        migrations.DeleteModel(
            name='ButtonFile',
        ),
        migrations.DeleteModel(
            name='ButtonMedia',
        ),
        migrations.DeleteModel(
            name='InlineButton',
        ),
    ]
