# Generated by Django 3.1.6 on 2021-10-10 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0010_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Изображение'),
        ),
    ]
