# Generated by Django 3.1.6 on 2021-10-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0011_auto_20211010_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
