# Generated by Django 3.1.7 on 2021-05-27 20:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст опроса')),
                ('is_send', models.BooleanField(default=False, verbose_name='Отправлено')),
                ('is_timer', models.BooleanField(default=False, verbose_name='Отложенная отправка')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата отправки')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
            },
        ),
        migrations.CreateModel(
            name='SendAll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130, verbose_name='Название рассылки')),
                ('text', models.TextField(max_length=500, verbose_name='Текст рассылки')),
                ('image', models.ImageField(blank=True, upload_to='send/', verbose_name='Изображение')),
                ('status', models.BooleanField(default=False, help_text='Служебное поле', verbose_name='Отправлено')),
                ('is_timer', models.BooleanField(default=False, verbose_name='Отложенная отправка')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата отправки')),
            ],
            options={
                'verbose_name': 'Рассылку по всем пользователям',
                'verbose_name_plural': 'Рассылки по всем пользователям',
            },
        ),
        migrations.CreateModel(
            name='SendUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130, verbose_name='Название рассылки')),
                ('text', models.TextField(max_length=500, verbose_name='Текст рассылки')),
                ('image', models.ImageField(blank=True, upload_to='send/', verbose_name='Изображение')),
                ('status', models.BooleanField(default=False, help_text='Служебное поле', verbose_name='Отправлено')),
                ('is_timer', models.BooleanField(default=False, verbose_name='Отложенная отправка')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата отправки')),
            ],
            options={
                'verbose_name': 'Рассылку по конкретным пользователям',
                'verbose_name_plural': 'Рассылки по конкретным пользователям',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=130, verbose_name='огин пользователя')),
                ('telegram_id', models.CharField(max_length=130, unique=True, verbose_name='ID пользователя')),
                ('fio', models.CharField(blank=True, max_length=130, verbose_name='ФИО')),
                ('gender', models.CharField(blank=True, max_length=130, verbose_name='Пол')),
                ('team', models.CharField(blank=True, max_length=130, verbose_name='Команда')),
                ('age', models.CharField(blank=True, max_length=130, verbose_name='Возраст')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130, verbose_name='Название группы')),
            ],
            options={
                'verbose_name': 'Группа пользователей',
                'verbose_name_plural': 'Группы пользователей',
            },
        ),
        migrations.CreateModel(
            name='UserForSend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='telegram.senduser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользователя для рассылки',
                'verbose_name_plural': 'Пользователи для рассылки',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='telegram.usergroup', verbose_name='Группа'),
        ),
        migrations.CreateModel(
            name='SendGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130, verbose_name='Название рассылки')),
                ('text', models.TextField(max_length=500, verbose_name='Текст рассылки')),
                ('image', models.ImageField(blank=True, upload_to='send/', verbose_name='Изображение')),
                ('status', models.BooleanField(default=False, help_text='Служебное поле', verbose_name='Отправлено')),
                ('is_timer', models.BooleanField(default=False, verbose_name='Отложенная отправка')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата отправки')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.usergroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Рассылку по группам пользователей',
                'verbose_name_plural': 'Рассылки по группам пользователей',
            },
        ),
        migrations.CreateModel(
            name='PollUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='telegram.poll', verbose_name='Опрос')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='PollGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.usergroup', verbose_name='Группа')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='telegram.poll', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='PollButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130, verbose_name='Ответ')),
                ('vote', models.IntegerField(default=0, verbose_name='Голоса')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='button', to='telegram.poll', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
            },
        ),
    ]
