# Generated by Django 3.1.7 on 2021-06-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0003_auto_20210530_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='None', max_length=130, verbose_name='Логин пользователя'),
        ),
    ]
