# Generated by Django 3.1.7 on 2021-06-10 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0004_auto_20210609_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130, verbose_name='Наименование')),
                ('sort', models.IntegerField(default=0, help_text='Чем меньше число, тем выше кнопка', verbose_name='Сортировка')),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
                'ordering': ['sort'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='size',
            field=models.CharField(blank=True, max_length=130, verbose_name='Размер футболки'),
        ),
    ]
