# Generated by Django 3.1.7 on 2021-06-16 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0005_auto_20210610_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, max_length=130, verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.CharField(blank=True, max_length=130, verbose_name='Роль в команде'),
        ),
    ]
