# Generated by Django 3.1.7 on 2021-06-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0006_auto_20210616_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendall',
            name='file',
            field=models.FileField(blank=True, upload_to='files/', verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='sendgroup',
            name='file',
            field=models.FileField(blank=True, upload_to='files/', verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='senduser',
            name='file',
            field=models.FileField(blank=True, upload_to='files/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='sendall',
            name='text',
            field=models.TextField(max_length=1500, verbose_name='Текст рассылки'),
        ),
        migrations.AlterField(
            model_name='sendgroup',
            name='text',
            field=models.TextField(max_length=1500, verbose_name='Текст рассылки'),
        ),
        migrations.AlterField(
            model_name='senduser',
            name='text',
            field=models.TextField(max_length=1500, verbose_name='Текст рассылки'),
        ),
    ]
