# Generated by Django 3.1.7 on 2021-06-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0007_auto_20210616_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendall',
            name='text',
            field=models.TextField(max_length=4000, verbose_name='Текст рассылки'),
        ),
        migrations.AlterField(
            model_name='sendgroup',
            name='text',
            field=models.TextField(max_length=4000, verbose_name='Текст рассылки'),
        ),
        migrations.AlterField(
            model_name='senduser',
            name='text',
            field=models.TextField(max_length=4000, verbose_name='Текст рассылки'),
        ),
    ]
