# Generated by Django 3.1.6 on 2021-09-15 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0009_auto_20210617_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupinline',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupinline',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pollgroup',
            name='group',
        ),
        migrations.RemoveField(
            model_name='pollgroup',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='sendgroup',
            name='group',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='date',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='is_timer',
        ),
        migrations.RemoveField(
            model_name='sendall',
            name='date',
        ),
        migrations.RemoveField(
            model_name='sendall',
            name='is_timer',
        ),
        migrations.RemoveField(
            model_name='senduser',
            name='date',
        ),
        migrations.RemoveField(
            model_name='senduser',
            name='is_timer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='size',
        ),
        migrations.RemoveField(
            model_name='user',
            name='team',
        ),
        migrations.DeleteModel(
            name='GroupInline',
        ),
        migrations.DeleteModel(
            name='PollGroup',
        ),
        migrations.DeleteModel(
            name='SendGroup',
        ),
        migrations.DeleteModel(
            name='UserGroup',
        ),
    ]
