# Generated by Django 3.1.6 on 2021-09-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0011_user_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bonus',
            field=models.IntegerField(default=0, verbose_name='Баллы'),
        ),
    ]
