# Generated by Django 3.1.6 on 2021-11-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0012_user_bonus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polluser',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='polluser',
            name='user',
        ),
        migrations.DeleteModel(
            name='SendAll',
        ),
        migrations.RemoveField(
            model_name='userforsend',
            name='send',
        ),
        migrations.RemoveField(
            model_name='userforsend',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='user',
            name='owner',
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(max_length=130, verbose_name='ID пользователя'),
        ),
        migrations.DeleteModel(
            name='PollUser',
        ),
        migrations.DeleteModel(
            name='SendUser',
        ),
        migrations.DeleteModel(
            name='UserForSend',
        ),
    ]
